sudo: false

language: node_js

node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm i -g yarn
  - yarn install

script:
  - npm test

after_success:
  - npm run test:coverage
  - bash <(curl -s https://codecov.io/bash)
